library(shiny)
library(broom)
library(survMisc)
library(survminer)
library(shinythemes)
library(DT)
library(dplyr)
library(ggrepel)


# ====================================================================================
tagList(
  navbarPage(
    theme = shinythemes::shinytheme("sandstone"),
    "TRGAted",
    tabPanel("Home",
             fluidRow(
               column(12, offset = 1,
                      mainPanel(
                                br(),
                                br(),
                                h3("Methods:"), "Survival Analysis performed in TRGAted is utilizes the survival (v2.41-3) and survminer (v0.4.1) R packages. Optimal cutpoints are based on the surv_cutpoint function in the survminer package,
                                finding the lowest log-rank p-value with the minimum proportional comparison set to 15% versus 85% of samples. Hazard ratio are derived from the Cox Proportional Hazard regression model and are based on the 
                                High-versus-Low comparison.", strong("Important Note:"), "With the smaller datasets in the TCGA, the methodology above can be biased by the law of small numbers, inflating hazard ratio, be careful with interpretations 
                                and conclusions. Currently, to counteract potential extreme biases based on small numbers, hazard ratios above 20 are automatically filtered from the data.",
                                br(),
                                br(),
                                h3("About the Data:"), "Level 4 data from the reverse-phase protein arrays for each cancer type were downloaded from the", a("TCPA Portal", href="http://tcpaportal.org/tcpa/"), "(Date Downloaded: 11/10/17). 
                                Data was scaled into z-scores and overall (OS) and recurrence-free survival (RFS) information was attached for each sample. Recurrence-free survival is defined by the NCI as 'the length of time after primary treatment for 
                                a cancer ends, that a patient survives without any signs or symptoms of that cancer.' Each dataset varies in size in terms of total samples quantified for protein and by survival information. A summary of the each 
                                dataset is found below, including total number of samples, samples with overall survival information, samples with recurrence-free survival information and total number of proteins quantified:",
                                br(),
                                br(),
                                DT::dataTableOutput("mytable1")
                                
                      )
               )
             )
    ),
      tabPanel("Survival Curve",
             sidebarPanel(
            selectInput(
            inputId = "dataset", 'Select Cancer', choices = list_of_datasets,
            selectize = FALSE
            ),
            selectInput(
              inputId = "survival", 'Select Survival', choices = c("Overall", "Recurrence-Free"),
              selectize = FALSE
            ),
            selectizeInput(
              inputId = "Protein", 'Select Protein(s)', choices = "placeholder1", multiple = TRUE
            ),
            radioButtons("cutoff", "Select Cut-off", choiceNames = list("Quartile","Tertile", "Median(+HR)","Optimal Cutoff(+HR)"), choiceValues = c(75,66,50,1), selected = 75),
            downloadButton('downloadPlot', 'Download Plot'),
            br(),
            br(),
            strong("Explanation:"), "The survival curve is generated by selecting the cancer type, survival type and protein (one or more). Selecting a cut-off will divide the samples into either 4 groups (quartile), 3 groups (tertile) or into 2 groups 
            (median or Optimal Cut-off) based on the protein selected. If multiple proteins are selected, the curve will be generated by taking the mean of the selected proteins and calculating the survival curve. Reported p-value is based on
            the log-rank test, while the hazard ratio is calculated for the high-versus-low comparison in a Cox Regression model (only available for the 2 group cut-off options)."
            ),
            mainPanel(plotOutput("kmplot", height= 600, width = 800), value =2 
            )
    ),
    
    tabPanel("Across Cancer",
      sidebarPanel(
      selectInput(
        inputId = "dataset2", 'Select Cancer', choices = list_of_datasets,
        selectize = FALSE
      ),
      selectInput(
        inputId = "survival2", 'Select Survival', choices = c("Overall", "Recurrence-Free"),
        selectize = FALSE
      ),
      radioButtons("cutoff2", "Select Cut-off", list("Quartile" = 75, "Tertile" = 66, "Median" = 50, "Optimal Cutoff" = 1), selected = 1),
      numericInput("adjusthigh", "Adjust Labeling of Poor Prognosis Markers:",
                  min = 1, max = NA,
                  value = 2.0),
      numericInput("adjustlow", "Adjust Labeling of Good Prognosis Markers:",
                  min = 0, max = 1,
                  value = 0.5),
      radioButtons("prop", "Show Proportion", list("No" = 1, "Yes" = 2), selected = 1),
      downloadButton('downloadPlot2', 'Download Plot'),
      br(),
      br(),
      strong("Explanation:"), "Here the plot will report the hazard ratio and -log10(P-value) across all probes in the given cancer type based on the survival type and cut-off selected. This is performed by iterating through the Cox Regression model. 
      Outputs are the hazard ratios for the single protein and -Log10P-value based on the Cox Regression calculations. By clicking the 'Show Proportion' button, the high (red) and low (blue) sample proportions can be seen for the volcano plot."
      ),
      mainPanel(plotOutput("volplot", height= 600, width = 800), value =2,
              br(),
              br(),
              strong("Note:"), "This may take some time depending on the size of the dataset examined. The adaptive labeling settings are based on Cox Hazard Ratio (HR) and will not label proteins that do not reach a significance 
              threshold of P<0.05. If you are experiencing an error message, adjust the cut-off and labeling strategy in order to have variables to graph."
                )
               ),
    
    tabPanel("Across Protein",
             sidebarPanel(
               selectInput(
                 inputId = "survival3", 'Select Survival', choices = c("Overall", "Recurrence-Free"),
                 selectize = FALSE
               ),
               selectizeInput(
                 inputId = "Protein2", 'Select Protein', choices = "placeholder1" 
               ),
               numericInput("adjusthigh1", "Adjust Labeling of Poor Prognosis Markers:",
                           min = 1, max = NA,
                           value = 2.0),
               numericInput("adjustlow1", "Adjust Labeling of Good Prognosis Markers:",
                           min = 0, max = 1,
                           value = 0.5),
               downloadButton('downloadPlot3', 'Download Plot'),
               br(),
               br(),
               strong("Explanation:"), "Here each survival hazard ratios for a single protein can be viewed across all the cancer types. This feature uses the optimal cut-off feature for both overall survival and recurrence-free survival."
             ),
             mainPanel(plotOutput("volplot2", height= 600, width = 800), value =2,
                       br(),
                       br()
                       
             )
    ),
    
    tabPanel("About Us",
             fluidRow(
               column(12, offset = 1,
                  mainPanel(h3("About Us"), "This was a collaborative coding project between several medical students and post-Docs at the University of Iowa Carver College of Medicine. Principally, the effort was supported by the NIH F30 CA206255 fellowship 
                            and RO1 CA200673. Importantly, these results here are in whole or in part based upon data generated by the TCGA Research Network; you can find out more about the Network and each dataset at the", 
                            a("NCI Genomic Data Commons.", href="https://gdc.cancer.gov/"), "More information on the work conducted in the lab can be found at the", a("Zhang Lab Website.", href="https://zhang.lab.uiowa.edu/"),
                            br(),
                            h3("How to Cite:"), "Currently we are under the submission process. We will update with the citation when we have one.",
                            br(),
                            h3("Questions:"), "Code for this is available on", a("Github", href="https://github.com/ncborcherding"), "with more detailed explanation of methodology. If you still have questions, please email the link below.",
                            br(),
                            h3("Contact:"), "Please email with any questions, comments, or suggestions to", a("Nick Borcherding.", href="mailto:ncborch@gmail.com")
                            )
                  )
               )
            )
  )
)





